http:
  routers:
    my-v1-router:
      rule: "PathPrefix(`/api/v1`)"
      entryPoints:
        - web
      service: my-service

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"
